# Generated by Django 3.2.5 on 2021-08-17 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite recipe',
                'verbose_name_plural': 'Favorite recipes',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True,
                                          verbose_name='name')),
                ('measurement_unit', models.CharField(
                    max_length=20,
                    verbose_name='measuring unit')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True,
                                          verbose_name='name')),
                ('text', models.TextField(max_length=1000,
                                          verbose_name='description')),
                ('cooking_time', models.IntegerField(validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message='Time must be >= 1 minute.')],
                    verbose_name='time')),
                ('image', models.ImageField(upload_to='media')),
                ('creation_date',
                 models.DateTimeField(auto_now=True, db_index=True,
                                      verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('amount', models.PositiveIntegerField(
                    verbose_name='amount of ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient in recipe',
                'verbose_name_plural': 'Ingredients in recipe',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Shopping cart',
                'verbose_name_plural': 'Shopping carts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True,
                                          verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True,
                                          verbose_name='slug')),
                ('color', models.CharField(max_length=100, unique=True,
                                           verbose_name='color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Following user',
                'verbose_name_plural': 'Following users',
            },
        ),
    ]
