# Generated by Django 3.2.5 on 2021-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=20,
                                   verbose_name='measuring unit'),
        ),
    ]
