# Generated by Django 3.2.5 on 2021-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20210808_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Recipe',
                     'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, db_index=True,
                                       verbose_name='Date of creation'),
        ),
    ]
