# Generated by Django 3.2.5 on 2021-08-15 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20210810_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[
                django.core.validators.MinValueValidator(
                    limit_value=1,
                    message='Time must be >= 1 minute.')],
                verbose_name='time'),
        ),
    ]
